import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function AboutPage() {
  return <main><SiteHeader />
    <section className="page-hero"><p className="eyebrow">About SolRise</p><h1>Every learner deserves to feel capable.</h1><p>SolRise Learning Academy pairs strong instruction with genuine care, helping students build the skills and self-belief they need for school and beyond.</p></section>
    <section className="content-split section"><div><p className="eyebrow">Our purpose</p><h2>We teach the whole learner.</h2></div><div><p>Progress begins when a student feels seen, supported, and appropriately challenged. Our educators take time to understand each learner&apos;s strengths, needs, interests, and goals before shaping an approach that fits.</p><p>Lessons are purposeful and encouraging. We celebrate growth, make room for questions, and help students develop habits that turn short-term wins into lifelong confidence.</p></div></section>
    <section className="educators section"><div className="educator-intro"><p className="eyebrow">Meet the team</p><h2>Experienced educators. Personal support.</h2><p>Two passionate teachers united by high expectations and a heart for student success.</p></div>
      <article className="educator-card"><div className="portrait dianne" role="img" aria-label="Dianne Gonzalez" /><div><span>Founder</span><h3>Dianne Gonzalez</h3><p>Dianne is the founder of SolRise Learning Academy and a highly respected certified math educator. Her student-centered approach combines high expectations with personalized support, empowering learners to overcome challenges and realize their full potential.</p></div></article>
      <article className="educator-card"><div className="portrait yamilka" role="img" aria-label="Yamilka Delgardo" /><div><span>Educator</span><h3>Yamilka Delgardo, M.Ed.</h3><p>With over 20 years of experience, Yamilka brings energy, encouragement, and meaningful fun to every lesson. She helps students build strong academic skills while discovering a genuine love for learning.</p></div></article>
    </section>
    <section className="values section"><p className="eyebrow">What guides us</p><div className="value-grid"><article><strong>01</strong><h3>Belonging first</h3><p>Students learn best when they feel safe, respected, and understood.</p></article><article><strong>02</strong><h3>Growth with purpose</h3><p>Clear goals and thoughtful feedback make progress visible and motivating.</p></article><article><strong>03</strong><h3>Confidence that lasts</h3><p>We equip learners to advocate for themselves and face new challenges.</p></article></div></section>
    <section className="page-cta"><h2>Let&apos;s help your learner rise.</h2><a className="button button-light" href="/contact">Start a conversation</a></section><SiteFooter /></main>;
}
