import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
export const metadata: Metadata = {
  title: "In-Person and Online Learning",
  description: "Learn how SolRise creates focused, interactive, and personalized tutoring experiences in person and online.",
  alternates: { canonical: "/how-we-learn" },
};
export default function HowPage(){return <main><SiteHeader/><section className="page-hero"><p className="eyebrow">How we learn</p><h1>Flexible learning, grounded in connection.</h1><p>Whether we meet face to face or online, every session is focused, interactive, and built around the learner in front of us.</p></section>
<section className="format-grid section"><article><span>01</span><h2>In-person learning</h2><p>A calm, focused environment where students receive direct guidance, hands-on practice, and space to think aloud. Ideal for learners who thrive on face-to-face connection and tangible materials.</p><ul><li>Personalized, real-time support</li><li>Hands-on learning tools</li><li>Focused academic setting</li></ul></article><article><span>02</span><h2>Online sessions</h2><p>Convenient, interactive instruction from home using shared screens, digital whiteboards, and engaging resources. Ideal for busy schedules and learners comfortable with technology.</p><ul><li>Flexible location and scheduling</li><li>Interactive digital tools</li><li>Seamless family convenience</li></ul></article></section>
<section className="values section soft"><p className="eyebrow">In every session</p><div className="value-grid"><article><strong>Notice</strong><h3>We listen first.</h3><p>We identify what the learner understands, where they feel stuck, and what motivates them.</p></article><article><strong>Practice</strong><h3>We make thinking active.</h3><p>Students explain, try, revise, and connect ideas instead of passively watching.</p></article><article><strong>Reflect</strong><h3>We make growth visible.</h3><p>Clear feedback helps learners recognize progress and know what comes next.</p></article></div></section>
<section className="page-cta"><h2>Let&apos;s find the format that fits.</h2><a className="button button-light" href="/contact">Tell us about your learner</a></section><SiteFooter/></main>}
